
<html>
<head>
<title>KOHA: Ingresar al INTRANET</title>

</head>
<body text="black" bgcolor="white" marginheight=0 marginwidth=0 leftmargin=0 topmargin=0 >

<table cellpadding=0 cellspacing=0 width="100%" border=0>
<tr BGCOLOR="#339999" >

	
<td valign=bottom width="90"><img src="/images/inside-top-clean.gif"
        width=80 height=50 alt="KOHA: Intranet" hspace=0 vspace=0 border=0></td>
<td><h1>Ingresar al Intranet de Koha</h1></td>

        
        </TR>




<tr valign=top>

        <td><img src="<!-- TMPL_VAR NAME='themelang' -->/images/inside-koha-bottom.gif"
        width=69 height=44 alt="KOHA" hspace=0 vspace=0 border=0 ></td>

        <td align=right><img src="<!-- TMPL_VAR NAME='themelang' -->/images/holder.gif"
        width=300 height=48 alt="" hspace=0 vspace=0 name="mouseover" ></a></td>

        </TR>

</TABLE>

<BLOCKQUOTE>
