

<script language="JavaScript" src="<!-- TMPL_VAR NAME='themelang' -->/includes/menu2/menu.js"></script>
<script language="JavaScript" src="<!-- TMPL_VAR NAME='themelang' -->/includes/menu2/menu_items.js"></script>
<script language="JavaScript" src="<!-- TMPL_VAR NAME='themelang' -->/includes/menu2/menu_tpl.js"></script>
<link rel="stylesheet" href="<!-- TMPL_VAR NAME='themelang' -->/includes/menu2/menu.css">

<script language="JavaScript">
	new menu (MENU_ITEMS, MENU_TPL);
</script>

