<!-- Aca se definen todos los mensajes de catalogacion -->

<script>

CAMPO_NO_PUEDE_ESTAR_EN_BLANCO= "[% 'El campo no puede estar en blanco' | i18n %]";
ESTE_CAMPO_NO_PUEDE_ESTAR_EN_BLANCO= "[% 'Este campo es requerido, no lo deje en blanco' | i18n %]";
ESTA_SEGURO_QUE_DESEA_BORRAROLO= "[% 'Está seguro que desea borrarlo?' | i18n %]";
HAY_BARCODES_REPETIDOS= "[% 'Hay barcodes repetidos' | i18n %]";
ELIJA_AL_MENOS_UN_EJEMPLAR= "[% 'Elija al menos un ejemplar para realizar la acción' | i18n %]";

</script>
