
<!-- ************************************Window Cambiar Password***************************************** -->
		<div id="contentWindow" class="formElemets">
		<center>
		  <ul>
			<li>
				<b>Nueva Contrase&ntilde;a:</b>
			</li>
			<li>
				<input id=newpassword class="inputFontNormal" size=20 type=password>
	  		</li>
			<li>
				<b>Repetir Contrase&ntilde;a: </b>
			<li>
			</li>
				<input id=newpassword1  class="inputFontNormal" size=20 type=password>
			</li>	
			<li>
				<input type=button onClick="verificarClaveUsuario();" 
				value="Confirme contrase&ntilde;a" class="button">
			</li>
		  </ul>
		</center>
		</div> <!--end div id="contentWindow"-->

<!-- *******************************Fin**Window Cambiar Password***************************************** -->