/* Tigra Menu items structure */
var MENU_ITEMS = [
	['Inicio', '/cgi-bin/koha/mainpage.pl'],
	['Cat&aacute;logo', '/cgi-bin/koha/busquedas/filtrado.pl', null,
		['--------B&uacute;squedas------', null],
		['B&uacute;squeda  Avanzada', '/cgi-bin/koha/busquedas/filtrado.pl'],
		['B&uacute;squeda Experta', '/cgi-bin/koha/busquedas/filtradoExperto.pl'],
		['--------Cat&aacute;logo--------', null],
		['Agregar Documento', '/cgi-bin/koha/catalogacion/estructura/agregarItem.pl'],
		['Busqueda Ejemplar', '/cgi-bin/koha/busquedas/adminEjemplares.pl'],
		['Estantes Virtuales', '/cgi-bin/koha/busquedas/estante.pl'],
		['---------MARC---------', null],
		['Mapeo Koha a MARC', '/cgi-bin/koha/catalogacion/kohaToMARC.pl'],
		['Servidores Z39.50', '/cgi-bin/koha/admin/z3950servers.pl'],
		['------Configuraci&oacute;n-----', null],
		['Creaci&oacute;n Catalogo', '/cgi-bin/koha/catalogacion/estructura/estructuraCatalo.pl'],
		['Tipos de documentos', '/cgi-bin/koha/admin/itemtypes.pl'],
		['Visualizaci&oacute;n OPAC', '/cgi-bin/koha/catalogacion/visualizacionOPAC/visualizacionOpac.pl'],
		['Importaci&oacute;n', '/cgi-bin/koha/importacion.pl'],
		['Control de Autoridades','', null,
			['Sin&oacute;nimos', '/cgi-bin/koha/catalogacion/configuracion/controlAutoridades/controlAutoridadesSinonimos.pl'],
			['Seud&oacute;nimos', '/cgi-bin/koha/catalogacion/configuracion/controlAutoridades/controlAutoridadesSeudonimos.pl'],
		]
	],
	['Usuarios', '/cgi-bin/koha/usuarios/reales/buscarUsuario.pl', null,
		['Usuarios Reales', '/cgi-bin/koha/usuarios/reales/buscarUsuario.pl'],
		['Usuarios Potenciales', '/cgi-bin/koha/usuarios/potenciales/buscarUsuario.pl'],
		['------------------------', null],
		['Agregar Usuario', '/cgi-bin/koha/members/memberentry.pl?type=Add'],
		['Agregar Organizaci&oacute;n', '/cgi-bin/koha/members/imemberentry.pl?type=Add'],
		['------------------------', null],
		['Generar Carnets','/cgi-bin/koha/reports/users-cards.pl']
	],

	['Circulaci&oacute;n', null, null,
		['Pr&eacute;stamos', '/cgi-bin/koha/circ/prestamos.pl'],
		['Devol. y  Renov.', '/cgi-bin/koha/circ/devoluciones.pl'],
		['Sanciones', '/cgi-bin/koha/circ/sanctions.pl']
	],
	['Par&aacute;metros', null, null,
		['Preferencias',  '/cgi-bin/koha/admin/preferencias.pl', null,
			['Preferencias', '/cgi-bin/koha/admin/preferencias.pl'],
			['------------------------', null],
			['Reportes Gen&eacute;ricos', '/cgi-bin/koha/admin/generic_reports.pl'],
			['Unid. de informaci&oacute;n', '/cgi-bin/koha/admin/branches.pl'],
			['Tablas de Referencias', '/cgi-bin/koha/admin/refs.pl'],
			['Tipos de documentos', '/cgi-bin/koha/admin/itemtypes.pl'],
			['Categor&iacute;a de usuarios', '/cgi-bin/koha/admin/categorie.pl'],
			['Tipos de pr&eacute;stamos', '/cgi-bin/koha/admin/issuetypes.pl'],
			['Valores autorizados', '/cgi-bin/koha/admin/authorised_values.pl'],
			['Admin. Libre Deuda', '/cgi-bin/koha/admin/adminLibreDeuda.pl'],
			['Feriados', '/cgi-bin/koha/admin/feriados.pl'],
			['Sanciones', '/cgi-bin/koha/admin/sanctions.pl'],
			['Thesaurus', '/cgi-bin/koha/admin/thesaurus.pl'],		
			['---------MARC---------', null],
			['Links Koha - MARC DB', '/cgi-bin/koha/admin/koha2marclinks.pl'],
			['Estructura de MARC', '/cgi-bin/koha/admin/marctagstructure.pl'],
			['Chequeo MARC', '/cgi-bin/koha/admin/checkmarc.pl'],
			['Servidores Z39.50', '/cgi-bin/koha/admin/z3950servers.pl']
		],
		['Herramientas', null, null,
			['Exportaci&oacute;n', '/cgi-bin/koha/export/marc.pl'],
			['Importaci&oacute;n', '/cgi-bin/koha/import/breeding.pl']
		]
	],
	['Reportes', null, null,
		['Reportes', '/cgi-bin/koha/reports/reports-home.pl', null,
			['Reportes Gen&eacute;ricos', '/cgi-bin/koha/reports/generic_reports.pl'],
			['Inventario', '/cgi-bin/koha/reports/inventory.pl'],
			['Signatura Topogr&aacute;fica', '/cgi-bin/koha/reports/inventory-sig-top.pl'],
			['Estantes Virtuales', '/cgi-bin/koha/reports/estantes.pl'],
			['Usuarios', '/cgi-bin/koha/reports/users.pl'],
			['Pr. sin devolver', '/cgi-bin/koha/reports/prestamos.pl'],
			['Reservas', '/cgi-bin/koha/reports/reservas.pl'],
			['Registro de actividades', '/cgi-bin/koha/reports/registro.pl'],
			['Registro de circulaci&oacute;n', '/cgi-bin/koha/reports/historicoCirculacion.pl'],
			['Actividades anuales','/cgi-bin/koha/reports/estadistica_Anual.pl'],
			['Generar Carnets','/cgi-bin/koha/reports/users-cards.pl'],
			['Generar Etiquetas','/cgi-bin/koha/reports/book-labels.pl'],
		],
		['Estad&iacute;sticas', '/cgi-bin/koha/reports/reports-home.pl',null,
			['Disp. de Ejem.','/cgi-bin/koha/reports/availability.pl'],
			['Hist&oacute;rico de Pr&eacute;stamos.','/cgi-bin/koha/reports/historico_Prestamos.pl'],
			['Hist&oacute;rico de Sanciones.','/cgi-bin/koha/reports/historicoSanciones.pl'],
			['Estad. de Prestamos.','/cgi-bin/koha/reports/estadisticas.pl'],
			['Logueo de B&uacute;squedas.','/cgi-bin/koha/reports/logueoBusqueda.pl'],
			['Usuarios por categor&iacute;a.','/cgi-bin/koha/reports/userEst.pl'],
			['Tipo de ejemplares.','/cgi-bin/koha/reports/itemtypes.pl'],
			['Niveles bibliogr&aacute;ficos.','/cgi-bin/koha/reports/levels.pl'],
			['Disponibilidad.','/cgi-bin/koha/reports/avail_year.pl'],
		],
	],
	['Ayuda', null, null,
		['Acerca de', '/cgi-bin/koha/about.pl']
	]
]; 
