
<!-- Librerias necesarias para manejar el Autocomplete -->
<script src="/includes/jquery/jquery.bgiframe.min.js"></script>
<script src="/includes/jquery/jquery.dimensions.js"></script>
<script src="/includes/jquery/jquery.autocomplete.js"></script>
<link href="/includes/jquery/jquery.autocomplete.css" type="text/css" rel="stylesheet">
<script src="/intranet-tmpl/blue/includes/AutocompleteHelper.js"></script>
