<br clear=all>
<p> &nbsp; </p>


</BLOCKQUOTE>

<CENTER>
<FONT SIZE=2  face="arial, helvetica">
<A HREF="/cgi-bin/koha/mainpage.pl">Inicio</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">Cat&aacute;logo</a> ||
<A HREF="/cgi-bin/koha/members-home.pl">Usuarios</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Adquisici&oacute;n</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">Circulaci&oacute;n</a> ||
<A HREF="/cgi-bin/koha/reports-home.pl">Reportes</a> ||
<A HREF="/cgi-bin/koha/admin-home.pl">Par&aacute;metros</a> ||
<A HREF="/cgi-bin/koha/about.pl">Acerca&nbsp;de	</a> || 
<A HREF="/cgi-bin/koha/help.pl">Ayuda </a>
</FONT>
</CENTER>
</BODY>

</HTML>
