
<!-- Librerias necesarias para manejar el WindowHelper -->
<script src="/includes/jquery/jquery.bgiframe.min.js"></script>
<script src="/includes/jquery/jquery.dimensions.js"></script>
<script src="/includes/jquery/ui.core.js"></script>
<script src="/includes/jquery/ui.draggable.js"></script>
<script src="/includes/jquery/ui.draggable.ext.js"></script>
<script src="/blue/includes/jquery/ui.mouse.js"></script>

