var objAH;var combinables=['titulo','autor','tipo','signatura','tipo_nivel3_id'];var noCombinables=['keyword','isbn','dictionary','codBarra','estante','tema'];var shouldScroll=false;function updateInfoBusquedas(responseText){$("#volver").hide();$("#filtrosBusqueda").slideUp('slow');$('#resultBusqueda').html(responseText);$("#resultBusqueda").slideDown("slow");zebra('datos_tabla');if(shouldScroll)
scrollTo('resultBusqueda');}
function highlightBusquedaCombinable(){var string=[];var classes=[];if($('#autor').val()!=''){classes.push('autor_result');}
if($('#titulo').val()!=''){classes.push('titulo_result');}
var combinables=['titulo','autor','signatura'];highlight(classes,combinables);}
function busquedaCombinable(){objAH=new AjaxHelper(updateBusquedaCombinable);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/busquedasDB.pl';objAH.titulo=$('#titulo').val();objAH.autor=$('#autor').val();objAH.signatura=$('#signatura').val();objAH.tipo_nivel3_name=$('#tipo_nivel3_id').val();objAH.tipoAccion='BUSQUEDA_AVANZADA';var radio=$(":checked");var tipo=radio[0].value;objAH.tipo=tipo;objAH.funcion='changePage';objAH.sendToServer();}
function updateBusquedaCombinable(responseText){updateInfoBusquedas(responseText);highlightBusquedaCombinable();}
function changePage(ini){objAH.changePage(ini);}
function ordenarPor(ord){objAH.sort(ord);}
function buscar(doScroll){var limite_caracteres=3;var cumple_limite=true;var cumple_vacio=true;if(doScroll)
shouldScroll=doScroll;if($.trim($('#keyword').val())!=''){if((jQuery.trim($('#keyword').val())).length<limite_caracteres){cumple_limite=false;}else{busquedaPorKeyword();}}else if(jQuery.trim($('#estante').val())!=''){if((jQuery.trim($('#estante').val())).length<limite_caracteres){cumple_limite=false;}else{buscarEstante();}}else if(jQuery.trim($('#dictionary').val())!=''){if((jQuery.trim($('#dictionary').val())).length<limite_caracteres){cumple_limite=false;}else{buscarPorDiccionario(ini);}}else if(jQuery.trim($('#codBarra').val())!=''){if((jQuery.trim($('#codBarra').val())).length<limite_caracteres){cumple_limite=false;}else{buscarPorCodigoBarra();}}else if(jQuery.trim($('#isbn').val())!=''){if((jQuery.trim($('#isbn').val())).length<limite_caracteres){cumple_limite=false;}else{buscarPorISBN();}}else if(jQuery.trim($('#tema').val())!=''){if((jQuery.trim($('#tema').val())).length<limite_caracteres){cumple_limite=false;}else{buscarPorTema();}}else if((jQuery.trim($('#titulo').val())!='')||(jQuery.trim($('#autor').val())!='')||(jQuery.trim($('#signatura').val())!='')){if((jQuery.trim($('#titulo').val())).length<limite_caracteres||(jQuery.trim($('#autor').val())).length<limite_caracteres||(jQuery.trim($('#signatura').val())).length<limite_caracteres){cumple_limite=false;}else{busquedaCombinable();}}else{cumple_vacio=false;}
if(!cumple_limite){jAlert(INGRESE_AL_MENOS_TRES_CARACTERES_PARA_REALIZAR_LA_BUSQUEDA,CATALOGO_ALERT_TITLE);}else if(!cumple_vacio){jAlert(INGRESE_DATOS_PARA_LA_BUSQUEDA,CATALOGO_ALERT_TITLE)}}
function buscarPorCodigoBarra(){objAH=new AjaxHelper(updateInfoBusquedas);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/busqueda.pl';objAH.codBarra=$('#codBarra').val();objAH.sendToServer();}
function highlightbuscarPorCodigoBarra(){var string=[];var classes=[];string[0]=$('#codBarra').val();classes[0]='titulo_result';classes[1]='autor_result';highlight(classes,string);}
function buscarPorTema(){objAH=new AjaxHelper(updateInfoBusquedas);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/tema.pl';objAH.tema=$('#tema').val();objAH.funcion='changePage';objAH.sendToServer();}
function buscarPorISBN(){objAH=new AjaxHelper(updateInfoBusquedas);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/busqueda.pl';objAH.isbn=$('#isbn').val();objAH.sendToServer();}
function buscarPorDiccionario(){objAH=new AjaxHelper(updateInfoBusquedas);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/diccionario.pl';objAH.dictionary=$('#dictionary').val();objAH.funcion='changePage';objAH.sendToServer();}
function busquedaPorKeyword(){objAH=new AjaxHelper(updateBusquedaPorKeyword);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/busquedasDB.pl';objAH.keyword=$('#keyword').val();objAH.match_mode=$('#match_mode').val();objAH.tipoAccion='BUSQUEDA_COMBINADA';objAH.funcion='changePage';objAH.sendToServer();}
function updateBusquedaPorKeyword(responseText){updateInfoBusquedas(responseText);var keyword=$('#keyword').val();var temp_keyword=replaceAccents(keyword);$('#keyword').val(temp_keyword);highlightBusquedaPorKeyword();$('#keyword').val(keyword);highlightBusquedaPorKeyword();}
function highlightBusquedaPorKeyword(){var string=[];var classes=[];string[0]='keyword';classes[0]='titulo_result';classes[1]='autor_result';highlight(classes,string);}
function buscarEstante(){objAH=new AjaxHelper(updateInfoBusquedas);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/estante.pl';objAH.viewShelfName=$('#estante').val();objAH.orden='title';objAH.funcion='changePage';objAH.sendToServer();}
function mostrarEstantes(){objAH=new AjaxHelper(updateMostrarEstantes);objAH.debug=true;objAH.url='../estanteVirtual.pl';objAH.funcion='changePage';objAH.sendToServer();}
function updateMostrarEstantes(responseText){$("#filtrosBusqueda").slideUp('slow');$('#resultBusqueda').html(responseText);$("#resultBusqueda").slideDown("slow");zebra('tablaresultado');}
function verEstanteVirtual(shelf){objAH=new AjaxHelper(updateVerEstanteVirtual);objAH.debug=true;objAH.url='../estanteVirtualDB.pl';objAH.shelves=shelf;objAH.tipo='VER_ESTANTE';objAH.funcion='changePage';objAH.sendToServer();}
function verSubEstanteVirtual(shelf){objAH=new AjaxHelper(updateVerEstanteVirtual);objAH.debug=true;objAH.url='../estanteVirtualDB.pl';objAH.shelves=shelf;objAH.tipo='VER_SUBESTANTE';objAH.funcion='changePage';objAH.sendToServer();}
function updateVerEstanteVirtual(responseText){$('#resultBusqueda').html(responseText);zebra('tablaresultado');$("#volver").hide();$("#busqueda").slideUp('fast');$("#resultBusqueda").slideDown("fast");}
function verTema(idtema,tema){objAH=new AjaxHelper(updateInfoBusquedas);objAH.debug=true;objAH.url='/cgi-bin/koha/busquedas/busqueda.pl';objAH.idTema=idtema;objAH.tema=tema;objAH.funcion='changePage';objAH.sendToServer();}
function cambiarEstadoCampos(campos,clase){for(i=0;i<campos.length;i++){$('#'+campos[i]).attr('class',clase);}}
function buscarPorAutor(idAutor){objAH=new AjaxHelper(updateInfoBusquedas);objAH.url='/cgi-bin/koha/busquedas/busquedasDB.pl';objAH.debug=true;objAH.funcion='changePage';objAH.idAutor=idAutor;objAH.tipoAccion="POR_AUTOR";objAH.sendToServer();}
function ordenar(ord){objAH.sort(ord);}
