var INFO_PRESTAMOS_ARRAY=new Array();var objAH;function infoPrestamo(){this.id3='';this.id3Old='';this.tipoPrestamo;}
function objeto_usuario(){this.text;this.ID;}
function detalleUsuario(nro_socio){objAH=new AjaxHelper(updateInfoUsuario);objAH.debug=true;objAH.cache=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/detalleUsuario.pl';objAH.nro_socio=nro_socio;objAH.sendToServer();}
function updateInfoUsuario(responseText){$('#detalleUsuario').slideDown('slow');$('#detalleUsuario').html(responseText);}
function detalleSanciones(nro_socio){objAH=new AjaxHelper(updateDetalleSanciones);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/usuarios/reales/detalleSanciones.pl';objAH.nro_socio=nro_socio;objAH.sendToServer();}
function updateDetalleSanciones(responseText){$('#sanciones').slideDown('slow');$('#sanciones').html(responseText);}
function detalleReservas(nro_socio,funcion){objAH=new AjaxHelper(funcion);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/detalleReservas.pl';objAH.nro_socio=nro_socio;objAH.sendToServer();}
function updateInfoReservas(responseText){$('#tablaReservas').slideDown('slow');$('#tablaReservas').html(responseText);zebra('tablaReservas');checkedAll('checkAllReservas','chkboxReservas');}
function detallePrestamos(nro_socio,funcion){objAH=new AjaxHelper(funcion);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/detallePrestamos.pl';objAH.nro_socio=nro_socio;objAH.sendToServer();}
function updateInfoPrestamos(responseText){$('#tablaPrestamos').slideDown('slow');$('#tablaPrestamos').html(responseText);zebra('tablaPrestamos');checkedAll('checkAllPrestamos','chkboxPrestamos');}
function realizarAccion(accion,id_table,funcion){var chck=$('#'+id_table).find(':checked');var array=new Array;var long=chck.length;if(long==0){jAlert(ELIJA_AL_MENOS_UN_EJEMPLAR);}else{for(var i=0;i<long;i++){array[i]=chck[i].value;}
objAH=new AjaxHelper(funcion);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+"/circ/circulacionDB.pl";objAH.tipoAccion=accion;objAH.datosArray=array;objAH.nro_socio=USUARIO.ID;objAH.sendToServer();}}
function generaDivPrestamo(responseText){var infoArray=new Array;infoArray=JSONstring.toObject(responseText);var html="<div class='divCirculacion'> <p class='fontMsgConfirmation'>";var i;for(i=0;i<infoArray.length;i++){var coma="";var infoPrestamoObj=new infoPrestamo();infoPrestamoObj.id3Old=infoArray[i].id3Old;INFO_PRESTAMOS_ARRAY[i]=infoPrestamoObj;var comboItems=crearComboDeItems(infoArray[i].items,'comboItems'+i,infoArray[i].id3Old);var comboTipoPrestamo=crearComboDeItems(infoArray[i].tipoPrestamo,'tiposPrestamos'+i);if((infoArray[i].autor!="")&&(infoArray[i].autor!=null)){html=html+infoArray[i].autor;coma=", ";};if((infoArray[i].titulo!="")&&(infoArray[i].titulo!=null)){html=html+coma+infoArray[i].titulo;coma=", ";};if((infoArray[i].edicion!="")&&(infoArray[i].edicion!=null)){html=html+coma+infoArray[i].edicion};html=html+"<br>C&oacute;digo de barras: "+comboItems;html=html+"<br>Tipo de pr&eacute;stamo: "+comboTipoPrestamo;}
html=html+"</p>";html=html+"<center><input type='button' value='Aceptar' onClick='prestar()'>";html=html+"<input type='button' value='Cancelar' onClick='cancelarDiv();'></center><br>";html=html+"</div>";$('#confirmar_div').html(html);scrollTo('confirmar_div');}
function crearComboDeItems(items_array,idSelect,itemSelected){var opciones='';var html="<select id='"+idSelect+"'>";var i;for(i=0;i<items_array.length;i++){opciones=opciones+"<option value="+items_array[i].value;if((itemSelected)&&(itemSelected==items_array[i].value)){opciones=opciones+" selected ";}
opciones=opciones+">"+items_array[i].label+"</option>";}
html=html+opciones+"</select>";return html;}
function prestar(){for(var i=0;i<INFO_PRESTAMOS_ARRAY.length;i++){INFO_PRESTAMOS_ARRAY[i].id3=$('#comboItems'+i).val();INFO_PRESTAMOS_ARRAY[i].barcode=$("#comboItems"+i+" option:selected").text();INFO_PRESTAMOS_ARRAY[i].tipoPrestamo=$('#tiposPrestamos'+i).val();INFO_PRESTAMOS_ARRAY[i].descripcionTipoPrestamo=$("#tiposPrestamos"+i+" option:selected").text();}
objAH=new AjaxHelper(updateInfoPrestarReserva);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/circulacionDB.pl';objAH.tipoAccion='PRESTAMO';objAH.datosArray=INFO_PRESTAMOS_ARRAY;objAH.nro_socio=USUARIO.ID;objAH.sendToServer();}
function updateInfoPrestarReserva(responseText){cancelarDiv();var infoHash=JSONstring.toObject(responseText);var messageArray=infoHash.messages;var ticketsArray=infoHash.tickets;var mensajes='';alert("sdafsdfsdfd");die();detalleReservas(USUARIO.ID,updateInfoReservas);ejemplaresDelGrupo(ID_N2);}
function cancelarDiv(){$('#confirmar_div').html('');}
function cancelarReserva(reserveNumber){jConfirm(ESTA_SEGURO_QUE_DESEA_CANCELAR_LA_RESERVA,'Info',function(is_confirmed){if(is_confirmed){objAH=new AjaxHelper(updateInfoCancelacion);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/circulacionDB.pl';objAH.tipoAccion='CANCELAR_RESERVA';objAH.nro_socio=USUARIO.ID;objAH.id_reserva=reserveNumber;objAH.sendToServer();}});}
function updateInfoCancelacion(responseText){var Messages=JSONstring.toObject(responseText);setMessages(Messages);detalleReservas(USUARIO.ID,updateInfoReservas);}
function generaDivDevolucion(responseText){var infoArray=new Array;INFO_PRESTAMOS_ARRAY=new Array();infoArray=JSONstring.toObject(responseText);var html="<div class='divCirculacion'> <p class='fontMsgConfirmation'>";var accion=infoArray[0].accion;html=html+infoArray[0].accion+":<br>";for(var i=0;i<infoArray.length;i++){INFO_PRESTAMOS_ARRAY[i]=infoArray[i].id_prestamo;if((infoArray[i].autor!="")&&(infoArray[i].autor!=null)){html=html+infoArray[i].autor;if((infoArray[i].titulo!="")&&(infoArray[i].titulo!=null)){html=html+", ";}}
if((infoArray[i].titulo!="")&&(infoArray[i].titulo!=null)){html=html+infoArray[i].titulo;}
if((infoArray[i].edicion!="")&&(infoArray[i].edicion!=null)){html=html+" - "+infoArray[i].edicion+"<br>"};html=html+" ("+infoArray[i].barcode+")<br>"
html=html+"<br>"}
html=html+"</p>";html=html+"<center><input type='button' value='Aceptar' onClick=devolver()>";html=html+"<input type='button' value='Cancelar' onClick='cancelarDiv();'></center><br>";html=html+"</div>";$('#confirmar_div').html(html);scrollTo('confirmar_div');}
function generaDivRenovacion(responseText){var infoArray=new Array;INFO_PRESTAMOS_ARRAY=new Array();infoArray=JSONstring.toObject(responseText);var html="<div class='divCirculacion'> <p class='fontMsgConfirmation'>";var accion=infoArray[0].accion;html=html+infoArray[0].accion+":<br>";for(var i=0;i<infoArray.length;i++){var infoDevRenObj=new infoPrestamo();infoDevRenObj.nro_socio=infoArray[0].nro_socio;infoDevRenObj.id_prestamo=infoArray[i].id_prestamo;infoDevRenObj.id3=infoArray[i].id3;infoDevRenObj.barcode=infoArray[i].barcode;INFO_PRESTAMOS_ARRAY[i]=infoDevRenObj;if((infoArray[i].autor!="")&&(infoArray[i].autor!=null)){html=html+infoArray[i].autor;if((infoArray[i].titulo!="")&&(infoArray[i].titulo!=null)){html=html+", ";}}
if((infoArray[i].titulo!="")&&(infoArray[i].titulo!=null)){html=html+infoArray[i].titulo;}
if((infoArray[i].edicion!="")&&(infoArray[i].edicion!=null)){html=html+" - "+infoArray[i].edicion+"<br>"};html=html+" ("+infoArray[i].barcode+")<br>"
html=html+"<br>"}
html=html+"</p>";html=html+"<center><input type='button' value='Aceptar' onClick=renovar()>";html=html+"<input type='button' value='Cancelar' onClick='cancelarDiv();'></center><br>";html=html+"</div>";$('#confirmar_div').html(html);scrollTo('confirmar_div');}
function renovar(){objAH=new AjaxHelper(updateInfoRenovar);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/circulacionDB.pl';objAH.tipoAccion='REALIZAR_RENOVACION';objAH.datosArray=INFO_PRESTAMOS_ARRAY;objAH.nro_socio=USUARIO.ID;objAH.sendToServer();}
function updateInfoRenovar(responseText){cancelarDiv();var infoHash=JSONstring.toObject(responseText);var messageArray=infoHash.messages;var ticketsArray=infoHash.tickets;for(i=0;i<messageArray.length;i++){setMessages(messageArray[i]);}
detallePrestamos(USUARIO.ID,updateInfoPrestamos);ejemplaresDelGrupo(ID_N2);}
function devolver(){objAH=new AjaxHelper(updateInfoDevolver);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/circulacionDB.pl';objAH.tipoAccion='REALIZAR_DEVOLUCION';objAH.datosArray=INFO_PRESTAMOS_ARRAY;objAH.nro_socio=USUARIO.ID;objAH.sendToServer();}
function updateInfoDevolver(responseText){}
function imprimirTicket(tickets){var comprobantes=new Array();if(tickets.length>0){for(i=0;i<tickets.length;i++){comprobantes[i]=tickets[i];}}
objAH=new AjaxHelper(updateImprimirTicket);objAH.debug=true;objAH.showOverlay=true;objAH.url=URL_PREFIX+'/circ/circulacionDB.pl';objAH.tipoAccion='IMPRIMIR_COMPROBANTE';objAH.comprobantes=comprobantes;objAH.sendToServer();}
function updateImprimirTicket(responseText){$('#ticket').html(responseText);$('#ticket').printElement({printBodyOptions:{styleToAdd:'color:#FFFFFF;',classNameToAdd:'comprobante'}});$('#ticket').hide();var html="<a id='link_comp' onclick='mostrarComprobante();'> Ver impresion</a>";$('.message_text').append(html);}
function mostrarComprobante(){$('#ticket').modal({containerCss:{backgroundColor:"#fff",color:"#000",},});}
