<div id="resultBusqueda"></div>
<div id="result"></div>

</div><!-- marco_datos -->
</div> <!--marco_contenido -->

</div></div>
	
</div>
      <div id="loading_items" class="loading_items"><br /></div>

</div>
<footer>
	<div id="marca"> 
	    <div id="footer-info">
		    [% IF titulo_nombre_ui %]
		        [% titulo_nombre_ui %]
		    [% ELSE %]
		        <a href="http://meran.linti.unlp.edu.ar" target="_blank">Meran</a>&nbsp;-&nbsp;Intranet
		    [% END %]
		    
		    &nbsp;@[% actual_year %]
	    </div>
	</div>
</footer>
</div> <!-- container_test -->
</body>
</html>
