
<script type="text/javascript">

    // MENSAJES PARA USUARIOS

    PASSWORDS_DISTINTAS = "[% 'Las claves son distintas, ingreselas nuevamente.' | i18n %]";

    PASSWORD_EN_BLANCO = "[% 'Las clave no puede estar en blanco, ingreselas nuevamente.' | i18n %]";

    LAS_CLAVES_SON_DISTINTAS= "[% 'Las claves son distintas. Ingreselas nuevamente.' | i18n %]";

    CAMBIO_DE_CONTRASENIA= "[% 'Cambio de Contraseña' | i18n %]";

    ESTA_SEGURO_QUE_DESEA_RESERVAR= '[% "Realmente desea reservar el ejemplar?" | i18n %]';

    FAVORITE_ADDED= '[% "Se agrego el favorito correctamente." | i18n %]';

    FAVORITE_ADDED_ERROR= '[% "No se pudo agregar el favorito" | i18n %]';

    FAVORITE_DELETED= '[% "Se elimino el favorito correctamente." | i18n %]';

    FAVORITE_CONFIRM_DELETE= '[% "Desea borrar el favorito?" | i18n %]';

    FAVORITE_DELETED_ERROR= '[% "No se pudo eliminar el favorito" | i18n %]';

    CATALOGO_TITLE= '[% "Alerta de Catalogo" | i18n %]';

    OPAC_ALERT_TITLE= '[% "Alerta de La Biblioteca" | i18n %]';

    POR_FAVOR_INGRESE_SU_APELLIDO   = "[% 'Por favor, ingrese su apellido' | i18n %]";
    POR_FAVOR_INGRESE_SU_NOMBRE     = "[% 'Por favor, ingrese su/s nombre/s' | i18n %]";
    POR_FAVOR_INGRESE_SU_MENSAJE    = "[% 'Por favor, ingrese su mensaje' | i18n %]";
    POR_FAVOR_INGRESE_UNA_DIR_DE_EMAIL_VALIDA= "[% 'Por favor, ingrese una direcci\u00f3n de email v\u00e1lida' | i18n %]";


</script>