
<script type="text/javascript">

    // MENSAJES PARA USUARIOS

    PASSWORDS_DISTINTAS = "[% 'Las claves son distintas, ingreselas nuevamente.' | i18n %]";

    PASSWORD_EN_BLANCO = "[% 'Las clave no puede estar en blanco, ingreselas nuevamente.' | i18n %]";

    LAS_CLAVES_SON_DISTINTAS= "[% 'Las claves son distintas.\nIngreselas nuevamente.' | i18n %]";

    CAMBIO_DE_CONTRASENIA= "[% 'Cambio de Contraseña' | i18n %]";

</script>