<!-- [% IF show_navlink %] -->
    <!-- B.1 MAIN NAVIGATION -->

        <!-- Navigation Level 3 -->
        <div class="round-border-topright"></div>
        <h1 class="first">Title</h1>

        <!-- Navigation with grid style -->
        <dl class="nav3-grid">
          <dt><a href="#">Navlink 11</a></dt>
          <dt><a href="#">Navlink 12</a></dt>
            <dd><a href="#">Navlink 121</a></dd>
            <dd><a href="#">Navlink 122</a></dd>
            <dd><a href="#">Navlink 123</a></dd>
          <dt><a href="#">Navlink 13</a></dt>
          <dt><a href="#">Navlink 14</a></dt>
          <dt><a href="#">Navlink 15</a></dt>
        </dl>
<!-- [% END %] -->