
<h1 class="pagetitle">Equipo Central</h1>
<hr class="clear-contentunit" />

 <h4><a href="http://www.cespi.unlp.edu.ar" target="_blank">CESPI</a> - <a href="http://www.linti.unlp.edu.ar" target="_blank">LINTI</a> - <a href="http://www.info.unlp.edu.ar" target="_blank">Facultad de Informática</a></h4> 
 <ul> 
     <li>Javier D&iacute;az</li>
     <li>Einar Lanfranco</li>
     <li>Mat&iacute;as Pagano</li>
     <li>Augusto Perez</li>
     <li>Miguel Carbone</li>
     <li>Gaspar Rajoy</li>
     <li>Magal&iacute; Defalco</li>
     <li>Francisco Raposeiras</li>
 </ul>

<br><br>

 <h4><a href="http://www.econo.unlp.edu.ar" target="_blank">Facultad de Ciencias Econ&oacute;micas</a></h4>
 <ul>
     <li>Mar&iacute;a Fernanda Pietroboni</li>
     <li>Mar&iacute;a Laura Asenjo</li>
     <li>Paula Gabriela Gonzalez</li>
     <li>Ana Mar&iacute;a Ca&ntilde;edo</li>
     
 </ul>

<br><br>

<h1 class="pagetitle">[% 'Datos de la Biblioteca' | i18n %]</h1>
<hr class="clear-contentunit" />

<ul> 
    <li>
        [% info_about.descripcion %]
    </li>
</ul>
