
<h1 class="pagetitle">Equipo Central</h1>
<hr class="clear-contentunit">

<h4>SIU y CESPI:</h4>
<ul>
    <li>Javier Díaz</li>
</ul>
<h4>LINTI - Facultad de Informática:</h4> 
<ul> 
    <li>Einar Lanfranco</li>
    <li>Matías Pagano</li>
    <li>Augusto Pérez</li>
    <li>Miguel Carbone</li>
    <li>Gaspar Rajoy</li>
</ul>

<br><br>

<h1 class="pagetitle">Datos de la Biblioteca</h1>
<hr class="clear-contentunit">

<ul> 
    <li>
        [% info_about.descripcion %]
    </li>
</ul>
