    <div class="footer">
      <p>@[% actual_year %] - [% ui.getNombre %]</p>
      <p class="credits">
          [% 'Powered by' | i18n %] <a href="http://koha.linti.unlp.edu.ar" target="_blank" title="MERAN">MERAN</a> 
          | <a href="http://validator.w3.org/check?uri=referer" target="_blank" title="Validate XHTML code">W3C XHTML 1.0</a> 
          | <a href="http://jigsaw.w3.org/css-validator/" target="_blank" title="Validate CSS code">W3C CSS 2.0</a>
      </p>
    </div>
</body>
</html>
