        <!-- Content unit - One column -->
        <h1 class="block">[% ui.getNombre %]</h1>
        <div class="column1-unit">
          <h1>[% 'Informaci&oacute;n de Contacto' | i18n %]</h1>
          <h3>[% 'Tel&eacute;fono' | i18n %]: [% ui.getTelefono %]</h3>
          <p>Puede comunicarse de 8:00 a 19:00 hs.</p>
          <h1><a>[% 'Direcci&oacute;n' | i18n %]: [% ui.getDireccion %]</a></h1>
          <h3>Aca???</h3>
          <p class="details">Posting details ...  </p>
        </div>
        <hr class="clear-contentunit" />
        <!-- Content unit - Two columns -->
