        <div class="subcontent-unit-border-green">
          <div class="round-border-topleft"></div><div class="round-border-topright"></div>
          <h1 class="green">[% 'Reservas Actuales' | i18n %]</h1>
          <a>&nbsp;[% 'Reservas asignadas' | i18n %]: </a>&nbsp;[% reservas_asignadas_count %]<br />
          <a>&nbsp;[% 'Reservas en espera' | i18n %]: </a>&nbsp;[% reservas_espera_count %]<br />
        </div>