<link rel="stylesheet" href="/includes/bootstrap/bootstrap.min.css">
<script src="/includes/bootstrap/js/bootstrap-tabs.js"></script>
<script src="/includes/bootstrap/js/bootstrap-alerts.js"></script>
<script src="/includes/bootstrap/js/bootstrap-modal.js"></script>
<script src="/includes/bootstrap/js/bootstrap-twipsy.js"></script>
<script src="/includes/bootstrap/js/bootstrap-buttons.js"></script>
<script src="/includes/bootstrap/js/bootstrap-scrollspy.js"></script>