<link rel="stylesheet" type="text/css" href="[% temas %]/[% user_theme_intra %]/includes/bootstrap.css">
<script src="http://twitter.github.com/bootstrap/assets/js/jquery.js"></script>
<script src="/includes/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/includes/jquery/bootbox.min.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-transition.js"></script>