
<!-- Librerias necesarias para manejar el WindowHelper -->
<script type="text/javascript" src="/includes/jquery/jquery.bgiframe.js"></script>
<script type="text/javascript" src="/includes/jquery/jquery.dimensions.js"></script>
<script type="text/javascript" src="/includes/jquery/ui.core.js"></script>
<script type="text/javascript" src="/includes/jquery/ui.draggable.js"></script>
<script type="text/javascript" src="/includes/jquery/ui.mouse.js"></script>
<link rel="stylesheet" type="text/css" href="[% temas %]/default/includes/windowHelper.css">

