
<!-- Librerias necesarias para manejar el WindowHelper -->
<link href="[% temas %]/default/includes/windowHelper.css" type="text/css" rel="stylesheet" />
<link type="text/css" href="/includes/jquery/ui/base/jquery.ui.core.css" rel="stylesheet" />
<link type="text/css" href="/includes/jquery/ui/base/jquery.ui.dialog.css" rel="stylesheet" />
<link type="text/css" href="/includes/jquery/ui/base/jquery.ui.theme.css" rel="stylesheet" />


<!--FIXME, ya esta en intranet top <script type="text/javascript" src="/includes/jquery/jquery.bgiframe.js"></script>-->
<!--<script type="text/javascript" src="/includes/jquery/jquery.dimensions-min.js"></script>-->
<!--<script type="text/javascript" src="/includes/jquery/ui.core-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui.draggable-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui.mouse-min.js"></script>-->

<!-- <script type="text/javascript" src="/includes/jquery/jquery.dimensions-min.js"></script> -->
<script type="text/javascript" src="/includes/jquery/ui/custom-min.js"></script>
<!--<script type="text/javascript" src="/includes/jquery/ui/core-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/draggable-min.js"></script>
<script type="text/javascript" src="/includes/jquery/ui/mouse-min.js"></script>-->
