/* Tigra Menu items structure */
var MENU_ITEMS = [
	['Inicio', '/cgi-bin/koha/mainpage.pl'],
	['Cat&aacute;logo', '/cgi-bin/koha/loadmodules.pl?module=search&marc=0&type=intranet', null,
		['B&uacute;squeda  Avanzada', '/cgi-bin/koha/loadmodules.pl?module=search&marc=0&type=intranet'],
		['B&uacute;squeda MARC', '/cgi-bin/koha/loadmodules.pl?module=search&marc=1&type=intranet'],
		['------------------------', null],
		['Estantes Virtuales', '/cgi-bin/koha/shelves.pl?startfrom=0'],
		['Agregar Libro', '/cgi-bin/koha/loadmodules.pl?module=addbiblio&type=intranet'],
		['Mantenimiento', '/cgi-bin/koha/maint/catmaintain.pl'],
		['Importaci&oacute;n MARC', '/cgi-bin/koha/importacionMarc.pl'],
		['Importaci&oacute;n', '/cgi-bin/koha/importacion.pl'],
		['Adquisici&oacute;n de ej.', '/cgi-bin/koha/loadmodules.pl?module=acquisitions']

	],
	['Usuarios', '/cgi-bin/koha/members-home.pl', null,
		['Usuarios Reales', '/cgi-bin/koha/members-home.pl'],
		['Usuarios Potenciales', '/cgi-bin/koha/members-home2.pl'],
		['------------------------', null],
		['Agregar Usuario', '/cgi-bin/koha/simpleredirect.pl?type=Agregar&chooseform=adult'],
		['Agregar Organizaci&oacute;n', '/cgi-bin/koha/simpleredirect.pl?type=Agregar&chooseform=organisation'],
		['------------------------', null],
		['Generar Carnets','/cgi-bin/koha/reports/users-cards.pl']
	],

	['Circulaci&oacute;n', '/cgi-bin/koha/circ/circulation.pl', null,
		['Pr&eacute;stamos', '/cgi-bin/koha/circ/circulation.pl'],
		['Devol. y  Renov.', '/cgi-bin/koha/circ/returns.pl'],
		['Transferencias', '/cgi-bin/koha/circ/branchtransfers.pl'],
		['Sanciones', '/cgi-bin/koha/circ/sanctions.pl']
	],
	['Par&aacute;metros', null, null,
		['Preferencias',  '/cgi-bin/koha/admin/systempreferences.pl', null,
			['Preferencias', '/cgi-bin/koha/admin/systempreferences.pl'],
			['------------------------', null],
			['Reportes Gen&eacute;ricos', '/cgi-bin/koha/admin/generic_reports.pl'],
			['Unid. de informaci&oacute;n', '/cgi-bin/koha/admin/branches.pl'],
			['Tablas de Referencias', '/cgi-bin/koha/admin/refs.pl'],
			['Tipos de documentos', '/cgi-bin/koha/admin/itemtypes.pl'],
			['Categor&iacute;a de usuarios', '/cgi-bin/koha/admin/categorie.pl'],
			['Tipos de pr&eacute;stamos', '/cgi-bin/koha/admin/issuetypes.pl'],
			['Valores autorizados', '/cgi-bin/koha/admin/authorised_values.pl'],
			['Admin. Libre Deuda', '/cgi-bin/koha/admin/adminLibreDeuda.pl'],
			['Feriados', '/cgi-bin/koha/admin/feriados.pl'],
			['Sanciones', '/cgi-bin/koha/admin/sanctions.pl'],
			['Thesaurus', '/cgi-bin/koha/admin/thesaurus.pl'],		
			['---------MARC---------', null],
			['Links Koha - MARC DB', '/cgi-bin/koha/admin/koha2marclinks.pl'],
			['Estructura de MARC', '/cgi-bin/koha/admin/marctagstructure.pl'],
			['Chequeo MARC', '/cgi-bin/koha/admin/checkmarc.pl'],
			['Servidores Z39.50', '/cgi-bin/koha/admin/z3950servers.pl']
		],
		['Herramientas', null, null,
			['Exportaci&oacute;n', '/cgi-bin/koha/export/marc.pl'],
			['Importaci&oacute;n', '/cgi-bin/koha/import/breeding.pl']
		]
	],
	['Reportes', null, null,
		['Todos', '/cgi-bin/koha/reports-home.pl'],
		['Reportes Gen&eacute;ricos', '/cgi-bin/koha/reports/generic_reports.pl'],
		['-------Reportes-------', null],
		['Reporte diario (hoy)', '/cgi-bin/koha/stats.pl?time=today'],
		['Reporte diario (ayer)', '/cgi-bin/koha/stats.pl?time=yesterday'],
		['Inventario', '/cgi-bin/koha/reports/inventory.pl'],
		['Signatura Topogr&aacute;fica', '/cgi-bin/koha/reports/inventory-sig-top.pl'],
		['Estantes Virtuales', '/cgi-bin/koha/reports/estantes.pl'],
		['Usuarios', '/cgi-bin/koha/reports/users.pl'],
		['Pr. sin devolver', '/cgi-bin/koha/reports/prestamos.pl'],
		['Reservas', '/cgi-bin/koha/reports/reservas.pl'],
		['Registro de actividades', '/cgi-bin/koha/reports/registro.pl'],
		['Registro de circulaci&oacute;n', '/cgi-bin/koha/reports/historicoCirculacion.pl'],
		['Actividades anuales','/cgi-bin/koha/reports/estadistica_Anual.pl'],
		['Generar Carnets','/cgi-bin/koha/reports/users-cards.pl'],
		['-----Estad&iacute;sticas-----', null],
		['Disp. de Ejem.','/cgi-bin/koha/reports/availability.pl'],
		['Historico de Pr&eacute;stamos.','/cgi-bin/koha/reports/historico_Prestamos.pl'],
		['Estad. de Prestamos.','/cgi-bin/koha/reports/estadisticas.pl'],
		['Logueo de B&uacute;squedas.','/cgi-bin/koha/reports/logueoBusqueda.pl'],
		['Usuarios por categor&iacute;a.','/cgi-bin/koha/reports/userEst.pl'],
	],
	['Ayuda', null, null,
		['Acerca de', '/cgi-bin/koha/about.pl']
	]
]; 
