use EconoV3 ;
GRANT SELECT on cat_nivel3 to intra@localhost identified by 'dev'; 
GRANT  on  cat_analitica                     ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_autor                         ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_autor_analitica               ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_colaborador                   ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_contenido_estante             ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_control_seudonimo_autor       ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_control_seudonimo_editorial   ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_control_seudonimo_tema        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_control_sinonimo_autor        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_control_sinonimo_editorial    ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_control_sinonimo_tema         ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_editorial                     ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_encabezado_campo_opac         ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_encabezado_item_opac          ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_estante                       ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_estructura_catalogacion       ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_estructura_catalogacion_opac  ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_historico_disponibilidad      ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_nivel1                        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_nivel1_repetible              ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_nivel2                        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_nivel2_repetible              ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_nivel3                        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_nivel3_repetible              ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_pref_mapeo_koha_marc          ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_ref_colaborador               ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_ref_tipo_nivel3               ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_tapa_amazon                   ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_tema                          ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_tema_analitica                ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_prestamo                     ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_ref_tipo_prestamo            ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_regla_sancion                ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_regla_tipo_sancion           ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_reserva                      ,SELECT, INSERT, UPDATE, DELETE,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_sancion                      ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_tipo_prestamo_sancion        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  circ_tipo_sancion                 ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_categoria_unidad_informacion ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_estructura_campo_marc        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_estructura_subcampo_marc     ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_feriado                      ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_informacion_referencia       ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_iso2709                      ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_palabra_frecuente            ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_preferencia_sistema          ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_relacion_unidad_informacion  ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_servidor_z3950               ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_tabla_referencia             ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_tabla_referencia_info        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_unidad_informacion           ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  pref_valor_autorizado             ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_disponibilidad                ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_dpto_partido                  ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_estado                        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_idioma                        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_localidad                     ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_nivel_bibliografico           ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_pais                          ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_provincia                     ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_soporte                       ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  ref_tipo_operacion                ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  rep_busqueda                      ,SELECT, INSERT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  rep_historial_busqueda            ,SELECT, INSERT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  rep_historial_circulacion         ,SELECT, INSERT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  rep_historial_prestamo            ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  rep_historial_sancion             ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  rep_registro_modificacion         ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  sessionqueries                    ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  sist_sesion                       ,SELECT, INSERT, UPDATE, DELETE,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  unavailable                       ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  uploadedmarc                      ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_estado                        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_permiso                       ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_persona                       ,SELECT, UPDATE,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_ref_categoria_socio           ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_ref_estado                    ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_ref_tipo_documento            ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_socio                         ,SELECT, UPDATE,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  usr_socio_relacionado             ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  z3950queue                        ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  z3950results                      ,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  perm_general,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  perm_circulacion,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  perm_reporte,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  perm_catalogo,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
GRANT  on  cat_portada_registro,SELECT,SELECT, INSERT, UPDATE, DELETE,ALL,ALTER,INSERT,UPDATE, DELETE, CREATE, DROP to intra@localhost; 
